task_worker_manager:
  logger:
    type: std
  queue:
    task:
      type: multiprocessing
    task_status:
      type: multiprocessing
    control:
      type: multiprocessing
  manager:
    type: multiprocessing
  rpc:
    address: 0.0.0.0
    port: 2333

scheduler:
  curr_node:
    uuid: abcd
    host: localhost
    port: 2333
  rpc_chooser:
    type: hash
  cron_scheduler:
    type: schedule
  argument_queue:
    type: multiprocessing
  lock:
    type: multiprocessing
  control:
    type: multiprocessing
    leader_node:
      uuid: aaaa
      host: localhost
      port: 2334

webserver:
  rpc_chooser:
    type: hash
  repository:
    uri: mysql+aiomysql://root:zqqqqz2000@127.0.0.1:3306/funtask
  service:
    host: localhost
    port: 2335
  task_worker_manager_nodes:
      - uuid: uuid1
        host: localhost
        port: 2333
