config:
  task_worker_manager:
    logger:
      type: std
    queue:
      type: multiprocessing
      host: localhost
      port: 3333
    manager:
      type: multiprocessing
    rpc:
      host: localhost
      port: 2333
      uuid: manager

  worker-scheduler:
    curr_node:
      uuid: worker
      host: localhost
      port: 2336
    rpc_selector:
      type: hash
    repository:
      uri: mysql+aiomysql://root:zqqqqz2000@127.0.0.1:3306/funtask
    cron_scheduler:
      type: schedule
    argument_queue:
      type: multiprocessing
      host: localhost
      port: 3333
    lock:
      type: multiprocessing
    manager_control:
      type: static
      nodes:
        - host: localhost
          port: 2333
          uuid: manager
    scheduler_control:
      type: static
      leader_node:
        uuid: leader
        host: localhost
        port: 2334
      worker_nodes:
        - uuid: worker
          host: localhost
          port: 2336
    as_leader:
      rebalanced_frequency:
        second: 1
    as_worker:
      max_sync_process_queue_number: 1000

  leader-scheduler:
    curr_node:
      uuid: leader
      host: localhost
      port: 2334
    manager_control:
      type: static
      nodes:
        - host: localhost
          port: 2333
          uuid: manager
    rpc_selector:
      type: hash
    repository:
      uri: mysql+aiomysql://root:zqqqqz2000@127.0.0.1:3306/funtask
    cron_scheduler:
      type: schedule
    argument_queue:
      type: multiprocessing
      host: localhost
      port: 3333
    lock:
      type: multiprocessing
    scheduler_control:
      type: static
      leader_node:
        uuid: leader
        host: localhost
        port: 2334
      worker_nodes:
        - uuid: worker
          host: localhost
          port: 2336
    as_leader:
      rebalanced_frequency:
        second: 1
    as_worker:
      max_sync_process_queue_number: 1000

  webserver:
    rpc_selector:
      type: hash
    repository:
      uri: mysql+aiomysql://root:zqqqqz2000@127.0.0.1:3306/funtask
    service:
      host: localhost
      port: 2335
    manager_control:
      type: static
      nodes:
        - uuid: selector
          host: localhost
          port: 2333
